FROM centos
USER root

MAINTAINER Maintainer_Name

RUN yum update -y
RUN yum install httpd procps-ng MySQL-python -y

RUN echo "PassEnv DB_SERVICE_SERVICE_HOST" >> /etc/httpd/conf/httpd.conf
RUN echo "The Web Server is Running" > /var/www/html/index.html
EXPOSE 80

# Start the service
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd"]
